In [7]:
import numpy as np
data = np.random.randn(2, 3)
print(data)

[[-1.06248328 -1.88364157  0.31758554]
 [ 0.02912194 -2.05324279  0.59761219]]


In [4]:
print(data * 10)

[[ -4.8534554   -9.29100926 -12.2838685 ]
 [ -8.55034075   2.68319917  -7.21500298]]


In [5]:
print(data+data)

[[-0.97069108 -1.85820185 -2.4567737 ]
 [-1.71006815  0.53663983 -1.4430006 ]]


In [8]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [10]:
data2 = [[1, 2 ,3 ,4], [5, 6, 7 ,8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
arr3 = np.arange(5)
print(arr3)

[0 1 2 3 4]


In [14]:
arr4 = np.zeros((2, 3))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
arr5 = np.ones((2, 3))
print(arr5)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
arr6 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr6)

[[1 2 3]
 [4 5 6]]


In [26]:
arr8=arr6*arr6
arr8

array([[ 1,  4,  9],
       [16, 25, 36]])

In [23]:
arr6^arr6

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [24]:
arr6 > arr6

array([[False, False, False],
       [False, False, False]])

In [28]:
val= arr6<arr8
print(val)

[[False  True  True]
 [ True  True  True]]


In [29]:
arr9 = np.arange(10)
print(arr9)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
print(arr9[5])

5


In [36]:
print(arr9[1:10])

[2 3 4 5 6 7 8 9]


In [37]:
arr9[5:8]=12
print(arr9)

[ 0  1  2  3  4 12 12 12  8  9]


In [52]:
arr2d=np.random.randn(3, 3)
print(arr2d)
print("\n-----------------------------------------\n")
print(arr2d[2])
print("\n-----------------------------------------\n")
print(arr2d[2, 2])

[[ 0.43836897 -0.69286177 -0.35794181]
 [-0.05327812  0.01438284  0.80255642]
 [ 0.02060561  0.38344482 -0.11474905]]

-----------------------------------------

[ 0.02060561  0.38344482 -0.11474905]

-----------------------------------------

-0.11474905392425538


In [59]:
arr3d=np.random.randn(2, 2, 3)
print(arr3d)
print("\n-----------------------------------------\n")
print(arr3d[1, 1, 1])

[[[ 0.43307074 -0.44827412  0.55142247]
  [ 0.02123609 -1.26951532  1.92554178]]

 [[ 0.80599265 -1.57807031 -0.57147759]
  [ 0.27237171 -1.52473355  0.26160669]]]

-----------------------------------------

-1.5247335525666503


In [61]:
arr_name={'bob','bom','box','bong','boy','beng'}
arr_element=np.random.randn(4, 6)
print(arr_name)
print(arr_element)

{'bob', 'boy', 'bong', 'box', 'bom', 'beng'}
[[ 1.95717017 -1.79388394  0.05314517 -0.09914709  0.48744647 -0.45855893]
 [ 0.59793117  0.85014969 -1.26869056 -1.79348337 -0.05997473 -0.18473053]
 [ 1.75959468  0.58600703  1.98706581 -0.01108996  0.85264988  0.15982134]
 [ 0.22520012 -0.59978556  0.10277983 -1.03297876 -0.6952508  -0.50065849]]


In [64]:
arr = np.empty((8, 4))
for i in arange(8):
    arr[i]=i
print(arr)

NameError: name 'arange' is not defined

In [2]:
frist_line = "I love "
number = 100
type1 = " dog."
frist_line2 = "My "
number2 = 100
type2 = " dogs are crazy."

sum1 = f"{frist_line}{number}{type1}"
sum2 = f"{frist_line2}{number2}{type2}"

print(sum1)
print(sum2)



I love 100 dog.
My 100 dogs are crazy.
